{
    "openapi": "3.0.1",
    "info": {
        "title": "Tr√©bol Session API",
        "version": "1.0.0",
        "description": "Resources to request new user accounts (register), logging in and out, request/update personal profile information, and request guest session tokens.",
        "contact": {
            "name": "Benjamin La Madrid",
            "email": "bg.lamadrid@gmail.com"
        },
        "license": {
            "name": "GNU GPLv3",
            "url": "https://www.gnu.org/licenses/gpl.txt"
        }
    },
    "paths": {
        "/guest": {
            "summary": "Guest session opener",
            "description": "",
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PersonProfile"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "headers": {
                            "Authorization": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Normal response; a guest token was generated. It is included in the response headers and body."
                    },
                    "403": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Response to an improper use; the user was already logged in or using a valid guest token."
                    },
                    "500": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "The resource found at this path is having a general malfunction. May be temporally, or permanently, unavailable."
                    }
                },
                "security": [
                    {

                    }
                ],
                "summary": "Start a guest session",
                "description": "POST personal information to generate a token for a temporary guest session."
            },
            "options": {
                "responses": {
                    "200": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Normal, empty response, should include CORS headers and only allow the POST method."
                    }
                },
                "summary": "Preflight check for guest session opener",
                "description": "Fetch OPTIONS for communicating with this resource."
            }
        },
        "/register": {
            "summary": "Account registrar",
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UserRegistration"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "headers": {
                            "Authorization": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Normal response; the registration was succesful and the user account was created. The user should log in with the input credentials."
                    },
                    "403": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "403 response"
                    },
                    "500": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "The resource found at this path is having a general malfunction. May be temporally, or permanently, unavailable."
                    }
                },
                "security": [
                    {

                    }
                ],
                "summary": "Request a new user account",
                "description": "POST details for a new user account, including its profile information."
            },
            "options": {
                "responses": {
                    "200": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Normal, empty response, should include CORS headers and only allow the POST method."
                    }
                },
                "summary": "Preflight check for account registrar",
                "description": "Fetch OPTIONS for communicating with this resource."
            }
        },
        "/login": {
            "summary": "Session opener",
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/LoginCredentials"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "headers": {
                            "Authorization": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Normal response; the credentials are correct, and an authorization token was generated. It is included in the response headers and body."
                    },
                    "403": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "The credentials were rejected."
                    },
                    "500": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "The resource found at this path is having a general malfunction. May be temporally, or permanently, unavailable."
                    }
                },
                "security": [
                    {

                    }
                ],
                "summary": "Start a logged-in session",
                "description": "POST credentials to authenticate, generate an authorization token and start a new session."
            },
            "options": {
                "responses": {
                    "200": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Normal, empty response, should include CORS headers and only allow the POST method."
                    }
                },
                "summary": "Preflight check for session opener",
                "description": "Fetch OPTIONS for communicating with this resource."
            }
        },
        "/profile": {
            "summary": "User profile information",
            "get": {
                "responses": {
                    "200": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/PersonProfile"
                                }
                            }
                        },
                        "description": "Normal response. Sends a representation of the profile information."
                    },
                    "403": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Response to improper use; the user is not logged in."
                    },
                    "500": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "The resource found at this path is having a general malfunction. May be temporally, or permanently, unavailable."
                    }
                },
                "security": [
                    {
                        "AuthorizedRequest": [
                        ]
                    }
                ],
                "summary": "Fetch current user's profile",
                "description": "GET the current user's stored profile information"
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PartialUserProfile"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Normal, empty response; the profile was updated successfully."
                    },
                    "403": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Response to improper use; the user is not logged in."
                    },
                    "500": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "The resource found at this path is having a general malfunction. May be temporally, or permanently, unavailable."
                    }
                },
                "security": [
                    {
                        "AuthorizedRequest": [
                        ]
                    }
                ],
                "summary": "Update current user's profile",
                "description": "PUT changes into the current user's profile information."
            },
            "options": {
                "responses": {
                    "200": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Normal, empty response, should include CORS headers and only allow the GET and PUT methods."
                    }
                },
                "security": [
                    {
                        "AuthorizedRequest": [
                        ]
                    }
                ],
                "summary": "Preflight check for user profile information",
                "description": "Fetch OPTIONS for communicating with this resource."
            }
        },
        "/logout": {
            "summary": "Session closer",
            "post": {
                "responses": {
                    "200": {
                        "headers": {
                            "Authorization": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Normal response; the session was terminated. Note that sending an expired token in the headers will also trigger this response, and not 403."
                    },
                    "403": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Response to improper use; the user is not logged in."
                    },
                    "500": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "The resource found at this path is having a general malfunction. May be temporally, or permanently, unavailable."
                    }
                },
                "security": [
                    {
                        "AuthorizedRequest": [
                        ]
                    }
                ],
                "summary": "Terminate current session",
                "description": "POST a request to close the currently opened session."
            },
            "options": {
                "responses": {
                    "200": {
                        "headers": {
                            "X-Requested-With": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Origin": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Methods": {
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "Access-Control-Allow-Headers": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Normal, empty response, should include CORS headers and only allow the POST method."
                    }
                },
                "summary": "Preflight check for session closer",
                "description": "Fetch OPTIONS for communicating with this resource."
            }
        }
    },
    "components": {
        "schemas": {
            "Empty": {
                "title": "Empty Schema",
                "description": "An object without properties.",
                "type": "object"
            },
            "PersonProfile": {
                "title": "Root Type for PersonProfile",
                "description": "Personal information about an individual.",
                "required": [
                    "email",
                    "name",
                    "address",
                    "idCard"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "idCard": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "address": {
                        "type": "string"
                    },
                    "phone1": {
                        "type": "integer"
                    },
                    "phone2": {
                        "type": "integer"
                    }
                },
                "example": {
                    "name": "Lorem ipsum dolor sit amet",
                    "idCard": "xxxxxxxxx",
                    "email": "address@example.com",
                    "address": "Excepteur sint occaecat cupidatat non proident",
                    "phone1": 1234567,
                    "phone2": 7654321
                }
            },
            "LoginCredentials": {
                "title": "Root Type for LoginCredentials",
                "description": "Data sent by an user to authenticate itself.",
                "required": [
                    "name",
                    "password"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                },
                "example": {
                    "name": "an username",
                    "password": "a password"
                }
            },
            "UserRegistration": {
                "title": "Root Type for UserRegistration",
                "description": "Credentials and personal information for a new user account.",
                "required": [
                    "password",
                    "profile",
                    "name"
                ],
                "type": "object",
                "properties": {
                    "password": {
                        "type": "string"
                    },
                    "profile": {
                        "$ref": "#/components/schemas/PersonProfile",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "idCard": {
                                "type": "string"
                            },
                            "address": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string"
                            },
                            "phone1": {
                                "format": "int32",
                                "type": "integer"
                            },
                            "phone2": {
                                "format": "int32",
                                "type": "integer"
                            }
                        }
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "example": {
                    "name": "an username",
                    "password": "a password",
                    "profile": {
                        "name": "Lorem ipsum dolor sit amet",
                        "idCard": "xxxxxxxxx",
                        "email": "address@example.com",
                        "address": "Excepteur sint occaecat cupidatat non proident",
                        "phone1": 1234567,
                        "phone2": 7654321
                    }
                }
            },
            "PartialUserProfile": {
                "title": "Root Type for PartialUserProfile",
                "description": "",
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "idCard": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "address": {
                        "type": "string"
                    },
                    "phone1": {
                        "type": "integer"
                    },
                    "phone2": {
                        "type": "integer"
                    }
                },
                "example": {
                    "name": "Lorem ipsum dolor sit amet",
                    "idCard": "xxxxxxxxx",
                    "email": "address@example.com",
                    "address": "Excepteur sint occaecat cupidatat non proident",
                    "phone1": 1234567,
                    "phone2": 7654321
                }
            }
        },
        "securitySchemes": {
            "AuthorizedRequest": {
                "scheme": "bearer",
                "type": "http",
                "description": "Requests including a Bearer token in their Authorization header."
            }
        }
    },
    "security": [
        {

        }
    ]
}